var test = require('tape')
var isAusPostcode = require('./dist/index').default

test('Invalid Australian Postcodes', t => {
  t.plan(12)
  t.false(isAusPostcode("0"))
  t.false(isAusPostcode("00"))
  t.false(isAusPostcode("000"))
  t.false(isAusPostcode("0000"))
  t.false(isAusPostcode("20000"))
  t.false(isAusPostcode("0100"))
  t.false(isAusPostcode("0100"))
  t.false(isAusPostcode("0300"))
  t.false(isAusPostcode("0400"))
  t.false(isAusPostcode("0500"))
  t.false(isAusPostcode("0600"))
  t.false(isAusPostcode("0700"))
})

test('Valid Australian Postcodes', t => {
  t.plan(12)
  t.true(isAusPostcode("0212"))
  t.true(isAusPostcode("0812"))
  t.true(isAusPostcode("0912"))
  t.true(isAusPostcode("1111"))
  t.true(isAusPostcode("2222"))
  t.true(isAusPostcode("3333"))
  t.true(isAusPostcode("4444"))
  t.true(isAusPostcode("5555"))
  t.true(isAusPostcode("6666"))
  t.true(isAusPostcode("7777"))
  t.true(isAusPostcode("8888"))
  t.true(isAusPostcode("9999"))
})